name: Release
on: [push]

jobs:
  windows:
    name: run on windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      shell: bash
      run: cargo build --release --features=fltk/fltk-bundled
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: resters-windows
        path: target/release/resters.exe
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Download deps
      run: sudo apt-get update && sudo apt-get install -y libpango1.0-dev libx11-dev libxext-dev libxft-dev libxinerama-dev libxcursor-dev libxrender-dev libxfixes-dev
      shell: bash
    - uses: actions/checkout@v2
    - name: Build
      shell: bash
      run: cargo build --release
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: resters-linux
        path: target/release/resters
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      shell: bash
      run: cargo build --release --features=fltk/fltk-bundled
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: resters-macos
        path: target/release/resters
